# Nombre de la aplicación (como aparecerá en Eureka)
spring.application.name=gateway-service
server.port=8080

# Configuración de Eureka Client
eureka.client.service-url.defaultZone=http://discovery:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${random.value}

# Configuración de Rutas Específicas
spring.cloud.gateway.server.webmvc.routes[0].id=MEMBERSHIP-ROUTE
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://MEMBERSHIP-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/v1/memberships/**




