# Nombre de la aplicación (como aparecerá en Eureka)
spring.application.name=api-gateway
server.port=8080

# Configuración de Eureka Client
eureka.client.service-url.defaultZone=http://service-registry:8761/eureka/
eureka.client.fetch-registry=true
eureka.client.register-with-eureka=true

eureka.instance.prefer-ip-address=true
eureka.instance.instance-id=${spring.application.name}:${random.value}

# Configuración de Rutas - Membership Service
spring.cloud.gateway.server.webmvc.routes[0].id=MEMBERSHIP-ROUTE
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://MEMBERSHIP-SERVICE
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/membership/**
spring.cloud.gateway.server.webmvc.routes[0].filters[0]=StripPrefix=1

# Configuración de Rutas - Scheduler Service
spring.cloud.gateway.server.webmvc.routes[1].id=SCHEDULER-ROUTE
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://SCHEDULER-SERVICE
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/scheduler/**
spring.cloud.gateway.server.webmvc.routes[1].filters[0]=StripPrefix=1

# Configuración de Rutas - Metrics Service
spring.cloud.gateway.server.webmvc.routes[2].id=METRICS-ROUTE
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://METRICS-SERVICE
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/metrics/**
spring.cloud.gateway.server.webmvc.routes[2].filters[0]=StripPrefix=1




