spring.application.name=scheduler-service

# Puerto fijo para el servicio
server.port=8082

# --- CONFIGURACIÓN MONGODB ---
spring.data.mongodb.uri=mongodb://redStak:qu1Nch1nK@scheduler-db:27017/booking_db?authSource=admin

# --- EUREKA CLIENT ---
eureka.client.service-url.defaultZone=http://service-registry:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.hostname=scheduler-service
eureka.instance.prefer-ip-address=false
eureka.instance.instance-id=${spring.application.name}:${server.port}

# Enable displaying Actuator endpoints in the OpenAPI documentation
springdoc.show-actuator=true

# Expose 'openapi' and 'swagger-ui' endpoints under the /actuator base path
management.endpoints.web.exposure.include=health,info,openapi,swagger-ui

# --- CONFIGURACIÓN RABBITMQ ---
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
spring.rabbitmq.template.retry.enabled=true
app.rabbitmq.queue=log-queue

