# 1. Identificación del servicio
spring.application.name=discovery
server.port=8761

# 2. Configuración de Eureka Server
# Un servidor de descubrimiento no debe registrarse a sí mismo
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# 3. URL del servicio (Ajustada a tu IP local física)
eureka.client.service-url.defaultZone=http://192.168.100.3:8761/eureka/

# 4. Configuración de la instancia para visibilidad en la red
#eureka.instance.hostname=192.168.100.3
eureka.instance.prefer-ip-address=true
#eureka.instance.ip-address=192.168.100.3

# 5. Optimización para entorno de desarrollo/examen
# Desactiva el modo de autoprotección para que Eureka elimine 
# instancias caídas rápidamente durante tus pruebas
eureka.server.enable-self-preservation=false

# Limpieza de logs para ver mejor lo que sucede
logging.level.com.netflix.eureka=INFO
logging.level.com.netflix.discovery=INFO