# 1. Identificación del servicio
spring.application.name=service-registry
server.port=8761

# 2. Configuración de Eureka Server
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false

# 3. URL del servicio para Docker
eureka.client.service-url.defaultZone=http://service-registry:8761/eureka/

# 4. Configuración de la instancia para Docker
eureka.instance.hostname=service-registry
eureka.instance.prefer-ip-address=false

# 5. Optimización para entorno de desarrollo
eureka.server.enable-self-preservation=false

# Logs
logging.level.com.netflix.eureka=INFO
logging.level.com.netflix.discovery=INFO